import { User } from '../models/User'

export const mockUsers = [
  new User({
    id: 5001,
    name: 'Admin User',
    phone: '0500000001',
    email: 'admin@dewedding.local',
    password: '123456',
    village: 'كسرى',
    role: 'admin',
    myEvents: [101, 104],
    phoneVerified: true,
  }).toJSON(),
  new User({
    id: 5002,
    name: 'General Supervisor',
    phone: '0500000002',
    email: 'general@dewedding.local',
    password: '123456',
    village: 'كسرى',
    role: 'generalSupervisor',
    myEvents: [102],
    phoneVerified: true,
  }).toJSON(),
  new User({
    id: 5003,
    name: 'Village Supervisor',
    phone: '0500000003',
    email: 'village@dewedding.local',
    password: '123456',
    village: 'كفرسميع',
    role: 'villageSupervisor',
    myEvents: [103],
    phoneVerified: true,
  }).toJSON(),
  new User({
    id: 5004,
    name: 'عميل كسرى',
    phone: '0526830531',
    email: 'user1@dewedding.local',
    password: '123456',
    village: 'كسرى',
    role: 'regular',
    myEvents: [101],
    phoneVerified: true,
  }).toJSON(),
  new User({
    id: 5005,
    name: 'كארם',
    phone: '0526576613',
    email: 'user2@dewedding.local',
    password: '123456',
    village: 'البقيعة',
    role: 'regular',
    myEvents: [],
    phoneVerified: true,
  }).toJSON(),
]
